version: '3.7'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      MSSQL_SA_PASSWORD: "Test1234!"  # Change this to your desired strong password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
